# Generated by Django 5.1 on 2024-08-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default='generaluser', max_length=50),
        ),
    ]
