# Generated by Django 5.1 on 2024-08-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_name_borrower_user_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='user',
            new_name='name',
        ),
    ]
