# Generated by Django 5.1 on 2024-08-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_user_borrower_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='book_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='book_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
