# Generated by Django 5.1 on 2024-08-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
