# Generated by Django 5.1 on 2024-08-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
